env: "prod" 

http_server:
  address: ":8888"

storage:
  postgres:
    url: "postgres://user:1234@localhost:5433/db"
    max_conns: 10
    min_conns: 3

auth:
  secret_key: "your-very-secure-secret-key-at-least-32-chars"
  access_expire_period_minutes: 15  
  refresh_token_expire_period_minutes: 1440 
  refresh_token_cookie_name: "medods_app_refresh_token"